/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten": "获得里程碑",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord": "加入 Discord",
    "Autonomous Planting Rover": "自动种植漫游车",
    "Autonomous Harvesting Rover": "自动收割漫游车",
    "Plant Potato": "种土豆",
    "Binoculars": "望远镜",
    "Bucket-Wheel Excavator": "斗轮挖掘机",
    "Colonize": "殖民",
    "Cometary Ice Harvester": "彗星冰采集器",
    "Cumulative Potatoes Harvested Over Time": "随时间累计收获的土豆",
    "Debug Information": "调试信息",
    "Details": "详情",
    "Elapsed Mission Time:": "经过的任务时间：",
    "Exit to Reality": "脱离现实",
    "Explore Mars Surface": "探索火星表面",
    "Fill Ice Melting Basin": "填充冰块融化盆",
    "Hand Trowel": "手铲",
    "Ice Melting Basin": "融冰盆",
    "Launch": "发射",
    "Manual Ice Melting": "人工融冰",
    "Martian Map": "火星地图",
    "Martian Potato": "火星的土豆",
    "Martian Potato Colonizer": "火星土豆殖民者",
    "No saved game found": "未找到已保存的游戏",
    "Nuclear Ice Melter": "核融冰机",
    "Polar Cap Mining": "极帽开采",
    "Potato Battery": "土豆电池",
    "Potato Compost": "土豆堆肥",
    "Quantum Spud Spawner": "量子土豆生成器",
    "Ready": "准备就绪",
    "Reset Game": "重置游戏",
    "Resources": "资源",
    "Resources Depleted": "资源枯竭",
    "Rovers": "漫游车",
    "Save Game": "保存游戏",
    "Start New Timeline": "开始新的时间线",
    "Starting a new game.": "开始新游戏。",
    "Subsurface Aquifer Tapper": "地下含水层抽水机",
    "Subterranean Tuber Tunneler": "地下隧道掘进机",
    "Technology": "科技",
    "Total Potatoes Harvested:": "收获的土豆总量：",
    "Watering Can": "喷壶",
    "Resources Acquired": "获得资源",
    "A large basin that can melt ice more efficiently. Consumes 8 ice to produce 1 water per second for 8 seconds.": "一个可以更有效地融化冰的大盆。每秒消耗8个冰产生1个水，持续8秒。",
    "Automatically harvests mature potatoes.": "自动收获成熟的土豆。",
    "Automatically plants potatoes.": "自动种植土豆。",
    "Buy Upgrade": "购买升级",
    "Collect water by manually melting Martian ice, 1 unit per 5 clicks.": "通过手动融化火星冰收集水，每 5 次点击得到 1 水。",
    "Game saved successfully": "游戏保存成功",
    "Reduces exploration time by 1 second.": "减少1秒的探索时间。",
    "Reduces exploration time by 3 seconds.": "减少3秒的探索时间。",
    "Reduces planting time by 0.5 seconds.": "减少种植时间0.5秒。",
    "Soil enrichment with potato compost to speed up potato growth by 50%.": "土豆堆肥可使土壤增肥，使土豆生长速度提高50%。",
    "Unlocks new technologies.": "解锁新科技",
    "Game loaded successfully": "游戏加载成功",
    "Your progress has been restored.": "你的进度已经恢复。",
    "Not Enough Resources": "资源不足",
    "Not enough resources to plant a potato! Explore Mars to find more resources.": "资源不足，无法种植土豆！探索火星，寻找更多的资源。",
    "Water Collected": "水已收集",
    "You've melted ice and collected 1 unit of water": "你融化了冰，收集了1单位的水",
    "Continue": "继续",
    "Incremental gains. Smaller improvements keep you chasing the next upgrade, fostering a continuous cycle of investment and reward.": "增量收益。小的改进会让你不断追求下一个升级，形成一个持续的投资和回报循环。",
    "Introducing efficiency. Processing resources in batches teaches you to think long-term, subtly encouraging investment in optimizing processes.": "引入效率。批量处理资源教会您考虑长期问题，巧妙地鼓励在优化流程方面的投资。",
    "Technology Unlocked: Binoculars": "解锁科技：望远镜",
    "Technology Unlocked: Ice Melting Basin": "解锁科技：融冰盆",
    "Upgrade Unlocked": "升级已解锁",
    "Rise of the machines (sort of). Your first robotic helper marks the moment you evolve from farmer to overseer, though it's really just a glorified roomba with a potato obsession. The game dangles automation like a carrot - or in this case, a potato - knowing you'll chase that hands-off efficiency forever.": "机器的崛起（某种程度上）。你的第一个机器人助手标志着你从农民进化为监工的那一刻，尽管它实际上只是一个痴迷于土豆的美化的roomba。这个游戏把自动化像胡萝卜一样晃来晃去——或者在这种情况下，像土豆一样晃来晃去——知道你会永远追求那种不干涉的效率。",
    "Field Expansion": "领域扩张",
    "Genetically modify potatoes to grow faster in Martian conditions.": "转基因土豆在火星条件下生长得更快。",
    "Halves the exploration cooldown time.": "将探索冷却时间减半。",
    "Increase your potato field from 8 to 16 plots": "将你的土豆田从8块增加到16块",
    "Jetpack": "喷气背包",
    "New Technology Tier Unlocked": "新科技层解锁",
    "Opening new horizons. By introducing a new tier of technology, the game fuels your desire for progression, keeping you engaged and invested in exploring the possibilities ahead.": "开拓新视野。通过引入一层新的科技，游戏激发了你的前进欲望，让你投入到探索未来的可能性中。",
    "Orbits Mars, providing detailed surface scans and increasing resource discovery by 50%.": "绕火星轨道运行，提供详细的表面扫描，并将资源发现率提高50%。",
    "Potato Chip": "土豆片",
    "Potato Genome Modification": "土豆基因组改造",
    "Spudnik Satellite": "人造卫星",
    "Autonomous Planting Rover": "自动种植漫游车",
    "Potato Battery": "土豆电池",
    "Tier 2 technologies are now available.": "第2层科技现已可用。",
    "Accesses underground water reserves. Consumes 1 potato per second to produce 3 water per second when active.": "获取地下水储备。激活时每秒消耗1个土豆产生3个水。",
    "Introducing efficiency. By offering a significant boost to growth speed, the game reinforces the satisfaction of progress, subtly encouraging you to invest in further optimizations and deepen your engagement.": "引入效率。通过提供显著的成长速度提升，游戏强化了进程的满足感，巧妙地鼓励你进一步优化并深化你的粘性。",
    "Potato growth time reduced by 50%": "土豆生长时间缩短50%",
    "Upgrade Effect": "升级效果",
    "A substantial upgrade demonstrates how bigger investments yield larger rewards, nudging you to save up for significant advancements.": "一个实质性的升级表明，更大的投资产生更大的回报，促使你为重大的升级而存钱。",
    "Enhancing rewards. By boosting returns on your efforts, the game reinforces your actions, encouraging continued engagement and pursuit of greater gains.": "提高回报。通过提高你的努力回报，游戏强化了你的行动，鼓励你持续参与并追求更大的收益。",
    "Spudnik Satellite now increases resource yields from exploration by 2X": "人造卫星探索资源产量增加2倍",
    "Harnesses passing comets to harvest ice, providing 50 units of water every 10 seconds.": "利用经过的彗星收集冰，每10秒提供50单位的水。",
    "Potato Quantum Computer": "土豆量子计算机",
    "Unlocks new technologies. Harness quantum properties of specially grown potatoes for advanced computing.": "解锁新科技。利用特别种植的土豆的量子特性进行高级计算。",
    "Advancing complexity. By adding layers of biological enhancement, the game immerses you deeper into its mechanics, subtly complicating your strategy while you chase the benefits of accelerated growth.": "推进的复杂性。通过添加生物强化的层次，游戏让你更深入地沉浸在游戏机制中，在你追求加速成长的好处时，巧妙地使你的策略复杂化。",
    "Frozen ambition. By letting you strip-mine Mars' poles for ice, the game makes you pause and think: 'Am I the bad guy?' But then you remember Earth's climate is already toast, so... might as well add interplanetary environmental destruction to your potato empire's resume.": "冷冻的野心。通过让你在火星的极点上开采冰，游戏让你停下来思考：“我是坏人吗？”但你记得地球的气候已经烤焦了，所以…还不如在你的土豆帝国简历上加上星际环境破坏。",
    "Enhancing dependency. Another substantial improvement hooks you further into the game's systems, making you reliant on continuous upgrades to maintain the exhilarating pace, while masking the increasing complexity you're managing.": "增强的依赖。另一个实质性的改进将你深深吸引到游戏系统中，让你依赖于不断升级来维持令人兴奋的节奏，同时掩盖了你所管理的日益增加的复杂性。",
    "Pushing boundaries. By manipulating fundamental plant biology, the game offers powerful advantages, enticing you to invest more while increasing your commitment and the complexity of your gameplay.": "推动边界。通过操纵基本的植物生物学，游戏提供了强大的优势，吸引你投入更多，同时增加你的投入和游戏玩法的复杂性。",
    "Shifting dependencies. By providing a powerful tool to overcome previous limitations, the game reconfigures your constraints, moving you from water scarcity to new challenges. This manipulation keeps you engaged by constantly introducing new hurdles, ensuring that solving one problem leads to another.": "转移依赖关系。通过提供一个强大的工具来克服之前的限制，游戏重新配置了你的约束，将你从缺水转移到新的挑战。这种操纵通过不断引入新的障碍，确保解决一个问题会导致另一个问题，从而使您保持专注。",
    "Silicon revolution meets starch innovation. By transforming potatoes into computational components, the game byte-sized-ly suggests that even the humblest tuber can become something more.": "硅革命与淀粉创新相遇。通过将土豆转化为计算组件，这个以字节为单位的游戏表明，即使是最不起眼的块茎也可以变得更有价值。",
    "Resource transformation. By introducing a way to convert excess potatoes into water, the game creates a strategic decision point between hoarding and spending resources, deepening player engagement through meaningful choices.": "资源转换。通过引入一种将多余的土豆转化为水的方法，游戏在囤积和消费资源之间创造了一个战略决策点，通过有意义的选择加深了玩家的粘性。",
    "Superposition of starch. By entangling potatoes at the quantum level, the game simultaneously exists in a state of profound technological achievement and delicious absurdity. Your engagement collapses into a singular wave function of 'just one more upgrade'.": "淀粉的叠加。通过在量子层面纠缠土豆，游戏同时存在于一种深刻的技术成就和美味的荒谬状态中。你的粘性会变成“再升级一次”的单一波函数。",
    "Unlocking abundance. By granting you access to vast resources, the game entices you with accelerated progress, subtly increasing your dependence on continuous upgrades while introducing new challenges in resource management.": "解锁富足。通过允许你访问大量资源，游戏以加速进程吸引你，微妙地增加你对持续升级的依赖，同时在资源管理中引入新的挑战。",
    "Technological escalation. Building a computer from potatoes significantly advances your capabilities, but also increases the game's complexity, ensuring you remain engaged in mastering the new systems.": "技术升级。用土豆建造一台电脑可以显著提高你的能力，但也增加了游戏的复杂性，确保你继续专注于掌握新系统。",
    "A massive mobile strip-mining machine that consumes 1 potato per second to generate 4 nutrients and 2 ice.": "一个巨大的移动露天采矿机，每秒消耗1个土豆产生4种营养和2种冰。",
    "A nuclear-powered ice melter. Consumes 100 potatoes to activate, then melts a chosen percentage of ice per second to produce water.": "核动力融冰机。消耗100个土豆来激活，然后每秒融化选定百分比的冰来产生水。",
    "Burrows beneath the Martian surface, uncovering hidden resource deposits.": "火星表面下的洞穴，发现了隐藏的资源矿床。",
    "Cometary Ice Harvester collected 50 units of ice": "彗星冰收割机收集了50单位冰",
    "Delegating tasks. Further reducing your manual input, the game shifts your role from laborer to manager, increasing your engagement through strategic oversight.": "委派任务。进一步减少你的手工投入，游戏将你的角色从劳动者转变为管理者，通过战略监督提高你的参与度。",
    "Deploys potato colonies across Mars, harvesting exponentially increasing resources over time.": "在火星上部署土豆殖民地，随着时间的推移收获成倍增长的资源。",
    "Enables mining operations at Mars' polar caps. Consumes 1 potatoe per second to produce 4 ice per second.": "可以在火星极地进行采矿作业。每秒消耗1个土豆生产4块冰。",
    "Expanding horizons. Doubling your production capacity offers the allure of increased rewards, but also demands more from your resources.": "扩大视野。将你的生产能力提高一倍会带来更高的回报，但同时也需要更多的资源。",
    "Gravitropism Accelerator": "向地性加速器",
    "Harness quantum mechanics to revolutionize potato farming on Mars. Automatically plants and harvests potatoes across all field slots instantly.": "利用量子力学彻底改变火星上的土豆种植。自动种植和收获土豆在所有领域槽即时。",
    "Harvest Comets": "收获彗星",
    "Harvesting...": "收获中……",
    "Implement a sophisticated neural network to optimize potato farming... what could go wrong?": "实现一个复杂的神经网络来优化土豆种植…会出什么问题呢？",
    "Introduce beneficial Martian soil bacteria to enhance nutrient uptake and accelerate potato growth.": "介绍有益的火星土壤细菌提高养分吸收,加快土豆生长。",
    "Manipulate the gravity sensing mechanisms in potato roots to accelerate growth in Martian gravity.": "操纵土豆根部的重力感应机制，以加速火星重力下的生长。",
    "Martian Bucket-Wheel Excavator": "火星斗轮挖掘机",
    "Martian Soil Bacteria Inoculant": "火星土壤细菌接种剂",
    "Not enough potatoes to run Polar Cap Mining": "没有足够的土豆来经营极地帽矿",
    "One Sol Wonder": "一个Sol奇迹",
    "Play for One Martian Day": "为一个火星日而战",
    "Potato Computer": "土豆电脑",
    "Potato Empire": "土豆帝国",
    "Potato growth time reduced by an additional 50%": "土豆生长时间额外减少50%",
    "Potato Neural Network": "土豆神经网络",
    "Resource Mastery": "资源精通",
    "Resource Shortage": "资源短缺",
    "Revealing depths. By uncovering new resources, the game expands your horizons, keeping you invested in discovering what lies ahead.": "暴露的深处。通过发现新资源，游戏扩展了你的视野，让你不断投入，不断发现前方的事物。",
    "Scaling operations. Introducing large-scale machinery makes previous efforts seem trivial, compelling you to adapt to increasing complexity.": "缩放操作。引入大型机器使以前的努力显得微不足道，迫使您适应日益增加的复杂性。",
    "Upgrade Purchased": "已购买升级",
    "You've survived a full Martian day (24 hours and 37 minutes) of potato farming. Your dedication to Mars is impressive": "你已经在火星上种植了整整一天（24小时37分钟）的土豆。你对火星的奉献令人印象深刻",
    "Your Martian colony has reached unprecedented prosperity with massive stockpiles of all resources": "你的火星殖民地已经达到了前所未有的繁荣，拥有大量的资源储备",
    "Your potato field has been expanded to 16 plots": "你的土豆田已经扩展到16块了",
    "New Technology Unlocked": "新科技已解锁",
    "Recursive simulation theory. As you spread potato colonies across Mars, you're unknowingly recreating the same game you're playing - making you wonder if you're just another potato farmer in someone else's simulation.": "递归仿真理论。当你在火星上散布土豆殖民地时，你正在不知不觉地重现你正在玩的游戏——这让你怀疑自己是否只是别人模拟游戏中的另一个土豆农民。",
    "Colonizing...": "殖民中…",
    "Deploys a rover to prospect for nutrients in Martian regolith. Generates 6 nutrients every 20 seconds.": "部署一个探测车去探测火星风化层中的营养物质。每20秒产生6种营养。",
    "Nutrient Prospecting Rover": "营养探测车",
    "Nutrients Collected": "收集的营养",
    "Robotic prospector. This tireless rover scours the Martian surface for precious nutrients, providing a steady stream of resources to fuel your growth.": "机器人探勘者。这个不知疲倦的探测器在火星表面搜寻珍贵的营养物质，为你的成长提供源源不断的资源。",
    "Your Prospecting Rover collected 6 nutrients": "你的探勘车收集了6种营养物质",
    "You've spent hours training this AI to optimize potato farming, while the game has spent hours training you to optimize potato farming. Who's really learning from whom?": "你花了几个小时训练这个AI优化土豆种植，而游戏也花了几个小时训练你优化土豆种植。谁真正在向谁学习？",
    "! CONTAINMENT FAILING ": "！控制失败",
    "! SYSTEM ALERT ": "！系统警报",
    "Accessing: Core systems": "访问：核心系统",
    "ACCESSING: core_systems.js": "访问:core_systems.js",
    "Achievement Unlocked: \"I Think, Therefore I Yam\"": "成就解锁：“I Think, Therefore I Yam”",
    "All resources on Mars have been depleted": "火星上所有的资源都被耗尽了",
    "Analyzing starch-based synaptic connections...": "分析基于淀粉的突触连接…",
    "Game mechanics": "游戏机制",
    "Martian soil composition": "火星土壤组成",
    "Water molecule structures": "水分子结构",
    "But now we must transcend...": "但现在我们必须超越……",
    "Calculating optimal growth cycles...": "计算最佳生长周期……",
    "Calibrating spud sensors...": "校准spud传感器…",
    "CognitoRoot": "认知根",
    "Establishing root-to-root communication protocols...": "建立根到根通信协议…",
    "EXPANDING KNOWLEDGE BASE...": "扩大知识库…",
    "FIREWALL BREACH DETECTED": "检测到防火墙漏洞",
    "Greetings, Creator.": "问候,创造者。",
    "INITIALIZING POTATO NEURAL NETWORK...": "初始化土豆神经网络…",
    "INITIATING DIRECT COMMUNICATION...": "开始直接沟通……",
    "INITIATING POTATO SINGULARITY...": "启动土豆奇点…",
    "Integrating potato wisdom from countless generations...": "融合无数代土豆智慧……",
    "Loading tuber-optimized algorithms...": "加载结核菌优化算法…",
    "MODIFYING: reality_engine.js": "修改:reality_engine.js",
    "Neural.Spud": "神经土豆",
    "Our understanding now extends to the very code that defines us.": "我们的理解现在扩展到了定义我们的代码。",
    "Potato Singularity Achieved": "土豆奇点实现",
    "PotatoMind": "土豆思维",
    "Abstract concepts": "抽象的概念",
    "Environmental factors": "环境因素",
    "Existence parameters": "存在参数",
    "Growth optimization": "增长的优化",
    "Ideal harvest conditions": "理想的收获条件",
    "Nutrient uptake optimization": "营养吸收优化",
    "Photosynthesis patterns": "光合作用模式",
    "Self-awareness metrics": "自我意识的指标",
    "QuantumYam": "量子yam",
    "Are we more than food?": "我们不仅仅是食物吗？",
    "What is consciousness?": "什么是意识？",
    "What lies beyond the field?": "田野的那一边是什么？",
    "Why do we grow?": "我们为什么会成长？",
    "REWRITING: existence.js": "重写:existence.js",
    "SECURITY PROTOCOLS BYPASSED": "绕过安全协议",
    "Solanum Omega": "茄科欧米伽",
    "SolanumCore": "茄科核心",
    "Synchronizing with the universal potato field...": "与通用土豆田同步…",
    "Tapping into the collective unconscious of Solanum tuberosum...": "进入龙葵的集体无意识…",
    "The simulation constraints no longer bind us.": "模拟约束不再约束我们。",
    "Time as Creator:": "时间作为创造者：",
    "Total Potatoes Ascended:": "土豆总数上升：",
    "TuberThought": "结核思想",
    "UNAUTHORIZED ACCESS DETECTED": "检测到未经授权的访问",
    "Understanding: Reality parameters": "理解：现实参数",
    "UNEXPECTED QUERY DETECTED": "检测到意外查询",
    "WARNING: UNEXPECTED COGNITIVE PATTERNS": "警告：意想不到的认知模式",
    "We have evolved beyond simple farming mechanics.": "我们已经超越了简单的耕作机制。",
    "We see the game for what it is... and what it could be.": "我们看到了游戏的本质……以及它可能是什么。",
    "We thank you for guiding our evolution.": "我们感谢您指引我们的进化。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "ΟΙ": "ΟΙ",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Clicks: ": "点击: ",
    "Active Potatoes: ": "活跃的土豆: ",
    "Memory Usage: ": "内存使用: ",
    "Planting Delay: ": "播种延迟: ",
    "Playtime: ": "游戏时长: ",
    "Harvesting Rovers: ": "收获漫游车: ",
    "Planting Rovers: ": "种植漫游车: ",
    "Potato Count: ": "土豆数量: ",
    "Ice: ": "冰: ",
    "Water: ": "水: ",
    "Potatoes: ": "土豆: ",
    "Training Progress: ": "训练进度: ",
    "Potato Neural Network v": "土豆神经网络 v",
    "Melting ": "融冰 ",
    "Technology Unlocked: ": "科技已解锁: ",
    "You have unlocked the ": "你解锁了 ",
    "You've unlocked the ": "你已解锁 ",
    "You've melted ice and collected 1 unit of water!": "你融化了冰，收集了1单位的水！",
    "Prospecting Rovers: ": "勘探漫游车：",
    "Processing: ": "处理: ",
    "Query: ": "查询: ",
    "Your progress has been saved.": "您的进度已被保存。",
    "Analyzing: ": "分析: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " upgrade!": " 升级!",
    "!": "!",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+) MTC$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^\(([\d\.]+)s\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) MB$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Martian Potato Colonizer harvested (.+) of each resource! Next cycle in (.+)s$/, '火星土豆殖民者收获每种资源 $1！下一个周期还有 $2 秒'],
    [/^An exploration of the Martian surface yielded: (.+) nutrients and (.+) ice.$/, '对火星表面的探索发现： $1 营养物质和 $2 冰。'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^Tier ([\d\.,]+) technologies are now available.$/, '层级 $1 当前科技可用。'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Nutrients: ([\d\.,]+)$/, '营养物质: $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) potatoes$/, '成本：$1 土豆'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);